
  __________________________________________________________________________________________________________
 |                                                                                                          |
 |                       AkademiWeb Açýk Kaynak Kodlu Dosya ve Ýçerik Yönetim Sistemi                       |
 |                                                                                                          |
 | -Sistemimiz Türkiye'de özgün olarak yapýlan sayýlý CMS'lerden biridir.                                   |
 | -Akademik Biliþim Konferansý '12 ve çeþitli teknoloji dergilerinde bildirisi yayýnlanmýþ bir sistemdir.  |
 |                                                                                                          |
 |                                      @author: Mustafa Özçelikörs                                         |
 |                                      @website: http://akademiweb.thewebblog.net                          |
 |                                      @contact: mozcelikors@gmail.com                                     |
 |                                                                                                          |
 |__________________________________________________________________________________________________________|


     KULLANIM SÖZLEÞMESÝ VE GÝZLÝLÝK POLÝTÝKASI
-------------------------------------------------------------------------------------------------------------
     Bu sistemi çeþitli yöntemlerle kopyalayarak resmi sitemiz harici daðýtým yapmak,
     Ücretli satýþta bulunmak,
     Bu sistemdeki bilgilerle oynayarak yeniden sunmak,
     Tamamýný veya belirli bir bölümünü parçalayarak internette yayýnlamak,
     Anahtar kodlarýný internette yayýnlamak,
     Copyright notunu silmek, 
     
         
     Türk Ceza Kanunu'nun Fikir ve Sanat Haklarý bölümüne ve Biliþim Suçlarý'na göre cezai suç sayýlýr.
     Bu durumlar farkedildiði takdirde cezai iþlemde bulunulacaktýr.
-------------------------------------------------------------------------------------------------------------




     UFAK BÝRKAÇ RÝCA
-------------------------------------------------------------------------------------------------------------
     Bu sistemi kullanýyorsanýz ve yararlý bir çalýþma olduðunu düþünüyorsanýz, lütfen çevrenizdekilerle de
     paylaþýn. Bu sistem sayesinde, bizlerin -reklam ücreti dahil- hiç bir geliri yoktur. Bu proje sadece 
     akademisyenlerin çektiði web sitesi sýkýntýsýna deva olmak için geliþtirilmiþtir. 

     Sisteminizi kullanýrken tespit ettiðiniz tüm sýkýntýlarý ve hatalarý bizlerle paylaþýp bu ücretsiz 
     projenin geliþmesine katký saðlayabilirsiniz.
     
     Ayrýca, sistemin tasarýmý veya  web programlama ile ilgili yardým almak istediðinizde de kapýmýz sonuna 
     kadar açýktýr.

        Saygý ve sevgilerimle,
        Mustafa Özçelikörs
        mozcelikors@gmail.com
        http://www.thewebblog.net
-------------------------------------------------------------------------------------------------------------